# Macro file for example PCT
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 0 
/run/verbose 0 
/event/verbose 0
/tracking/verbose 0 
/run/setCutForRegion myPhantom 1.0 mm
/control/execute parallelbeam.mac